# Generated by Django 5.1.4 on 2026-02-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tenant_name',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True),
        ),
    ]
