# Generated by Django 5.1.4 on 2026-02-15 11:22

import helpers.db.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_tenant_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="tla",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=3,
                null=True,
                unique=True,
                validators=[helpers.db.validators.validate_tla],
            ),
        ),
    ]
