# Generated by Django 5.1.4 on 2026-02-15 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0004_tenant_tla"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("version", models.CharField(default="1.0.0", max_length=30)),
                ("is_default_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SchemaTable",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("platform", "Platform"), ("tenant", "Tenant")],
                        default="platform",
                        max_length=20,
                    ),
                ),
                (
                    "table_key",
                    models.SlugField(
                        help_text="Logical key. Physical table is generated as tbl_<table_key>.",
                        max_length=63,
                    ),
                ),
                ("display_name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schema_tables",
                        to="schemadata.module",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for platform-level metadata table definitions.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema_tables",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["table_key"],
            },
        ),
        migrations.CreateModel(
            name="SchemaField",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_key", models.SlugField(max_length=63)),
                ("column_name", models.SlugField(max_length=63)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("text", "Text"),
                            ("integer", "Integer"),
                            ("bigint", "Big Int"),
                            ("boolean", "Boolean"),
                            ("datetime", "Date Time"),
                            ("date", "Date"),
                            ("json", "JSON"),
                            ("uuid", "UUID"),
                            ("decimal", "Decimal"),
                            ("reference", "Reference"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_nullable", models.BooleanField(default=True)),
                ("is_unique", models.BooleanField(default=False)),
                ("is_indexed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
                ("precision", models.PositiveIntegerField(blank=True, null=True)),
                ("scale", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "reference_table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referenced_by",
                        to="schemadata.schematable",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="schemadata.schematable",
                    ),
                ),
            ],
            options={
                "ordering": ["table__table_key", "column_name"],
            },
        ),
        migrations.CreateModel(
            name="TenantModuleSubscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("disabled", "Disabled"),
                            ("hidden", "Hidden"),
                        ],
                        default="enabled",
                        max_length=20,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_subscriptions",
                        to="schemadata.module",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_subscriptions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant__subdomain", "module__key"],
            },
        ),
        migrations.CreateModel(
            name="UpdateSet",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("previewed", "Previewed"),
                            ("committed", "Committed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_sets",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UpdateSetItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_type", models.CharField(max_length=60)),
                ("object_id", models.UUIDField()),
                ("operation", models.CharField(max_length=30)),
                ("before_snapshot", models.JSONField(blank=True, default=dict)),
                ("after_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "update_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="schemadata.updateset",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="schematable",
            constraint=models.UniqueConstraint(
                fields=("tenant", "table_key"), name="uq_schema_table_tenant_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="schemafield",
            constraint=models.UniqueConstraint(
                fields=("table", "field_key"), name="uq_schema_field_key_per_table"
            ),
        ),
        migrations.AddConstraint(
            model_name="schemafield",
            constraint=models.UniqueConstraint(
                fields=("table", "column_name"), name="uq_schema_column_per_table"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tenantmodulesubscription",
            unique_together={("tenant", "module")},
        ),
        migrations.AlterUniqueTogether(
            name="updateset",
            unique_together={("tenant", "name")},
        ),
    ]
