# Generated by Django 5.1.4 on 2026-02-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformcore', '0002_remove_module_description_tenantsubscription'),
        ('tenants', '0003_tenant_tenant_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TenantSubscription',
            new_name='TenantModule',
        ),
    ]
