# Generated by Django 5.1.4 on 2026-02-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformcore', '0003_rename_tenantsubscription_tenantmodule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantmodule',
            old_name='created_at',
            new_name='activated_at',
        ),
        migrations.AlterField(
            model_name='tenantmodule',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
