# Generated by Django 5.1.4 on 2026-02-17 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformcore', '0002_remove_module_description_tenantsubscription'),
        ('subscriptions', '0022_usersubscription_timestamp_usersubscription_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platformcore.module'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='provisioned',
            field=models.BooleanField(default=False),
        ),
    ]
