# Generated by Django 5.1.4 on 2026-02-16 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaengine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metafield',
            old_name='unique',
            new_name='read_only',
        ),
        migrations.AlterUniqueTogether(
            name='metafield',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='metafield',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metafield',
            name='help_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metafield',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metafield',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('choice', 'Choice'), ('reference', 'Reference')], max_length=20),
        ),
        migrations.CreateModel(
            name='MetaChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='metaengine.metafield')),
            ],
        ),
        migrations.RemoveField(
            model_name='metafield',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='metafield',
            name='sys_id',
        ),
    ]
