# Generated by Django 5.1.4 on 2026-02-17 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metaengine', '0002_rename_unique_metafield_read_only_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicRecord',
        ),
    ]
