# Generated by Django 5.1.4 on 2026-02-17 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaengine', '0003_delete_dynamicrecord'),
        ('platformcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatable',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metatable',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_tables', to='platformcore.module'),
        ),
    ]
