# Generated by Django 5.1.4 on 2026-02-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaengine', '0004_metatable_is_template_metatable_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='metafield',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
    ]
